### PR TITLE
Add page3

### PR DESCRIPTION
**Pull request by michalgluszak**

### CODE REVIEW

**Comment by v0lff** [comment]
rhytaratjfdjghetj

**Comment by michalgluszak** [comment]
dobra praca

**Comment by Zykfrydes** [comment]
NO TEGO TEN DOBRE

**Comment by Zykfrydes** [comment]
NO TEGO TEN DOBRA PRAC ***** ***

**Review by v0lff — APPROVED** [review]

**Review by Zykfrydes — APPROVED** [review]

**Pull request merged**
